parameters:
#    enbaby_redirect.example.class: Enbaby\RedirectBundle\Example

services:
#    enbaby_redirect.example:
#        class: %enbaby_redirect.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
