parameters:
#    enbaby_audio_lib.example.class: Enbaby\AudioLibBundle\Example

services:
#    enbaby_audio_lib.example:
#        class: %enbaby_audio_lib.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
